# Generated by Django 5.2 on 2025-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
